(* General *)
let cNUM_TEAMS = 2
let cUPDATE_TIME = 0.05
let cMAX_WAIT_CONNECTION_TIME = 10.
let cDEFAULT_PORT_NUMBER = 10500
let cDEFAULT_GUI_PORT_NUMBER = 10501
let cDEFAULT_BOT_PORT_NUMBER = 10502

(* Board *)
let cTIME_LIMIT = 60.
let cBOARD_WIDTH = 680
let cBOARD_HEIGHT = 680
let cBOARD_SIZE = (cBOARD_WIDTH, cBOARD_HEIGHT)

(* Game *)

let cINITIAL_LIVES = 3
let cINITIAL_BOMBS = 3

let cBOMB_DURATION = 50

let cGRAZE_POINTS = 100
let cPOWER_POINTS = 1000
let cKILL_POINTS = 10000

let cCHARGE_RATE = 100
let cCHARGE_MAX = 10000

let cINVINCIBLE_FRAMES = 40

let cUNFOCUSED_SPEED = 8
let cFOCUSED_SPEED = 4
let cHITBOX_RADIUS = 4
let cGRAZE_RADIUS = 50

let cSPREAD_NUM = 20
let cSPREAD_RADIUS = 15
let cSPREAD_SPEED = 4
let cSPREAD_COST = 500

let cTRAIL_RADIUS = 30
let cTRAIL_SPEED_STEP = 3
let cTRAIL_NUM = 6
let cTRAIL_COST = 5000
let cTRAIL_ANGLE = 30

let cBUBBLE_RADIUS = 50
let cBUBBLE_SPEED = 24
let cBUBBLE_COST = 3000

let cPOWER_RADIUS = 30
let cPOWER_SPEED = 5

let cACCEL_LIMIT = 0.25

let cUFO_SPAWN_INTERVAL = 200
let cUFO_SPEED = 6
let cUFO_RADIUS = 30
let cUFO_HITS = 10
let cUFO_POWER_NUM = 10
let cUFO_SCATTER_RADIUS = 45
let cUFO_MOVE_INTERVAL = 30
